#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Privy – one-time Supabase setup
# Run this once from your project root:  bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

echo ""
echo "╔══════════════════════════════════════╗"
echo "║   Privy – Supabase Setup Script      ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ── 1. Check Supabase CLI is installed ───────────────────────────────────────
if ! command -v supabase &> /dev/null; then
  echo "❌  Supabase CLI not found."
  echo "    Install it: https://supabase.com/docs/guides/cli/getting-started"
  exit 1
fi

# ── 2. Get project status (URL + keys) ───────────────────────────────────────
echo "⏳  Fetching Supabase project info..."
STATUS=$(supabase status 2>&1)

if echo "$STATUS" | grep -q "supabase local development setup is running"; then
  # ---- LOCAL dev mode (supabase start) ----
  echo "✅  Local Supabase detected."
  API_URL=$(echo "$STATUS" | grep "API URL" | awk '{print $NF}')
  ANON_KEY=$(echo "$STATUS" | grep "anon key" | awk '{print $NF}')
else
  # ---- Remote / linked project ----
  echo "✅  Remote Supabase project detected."
  # Try to extract from status output (works when project is linked via `supabase link`)
  API_URL=$(echo "$STATUS" | grep -i "api url\|API URL" | awk '{print $NF}')
  ANON_KEY=$(echo "$STATUS" | grep -i "anon key" | awk '{print $NF}')

  # Fallback: let the user paste them
  if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ]; then
    echo ""
    echo "  Could not auto-detect project URL/key from \`supabase status\`."
    echo "  Open https://supabase.com/dashboard → your project → Settings → API"
    echo ""
    read -rp "  Paste your Project URL (e.g. https://xxxxx.supabase.co): " API_URL
    read -rp "  Paste your anon / public key: " ANON_KEY
  fi
fi

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ]; then
  echo "❌  Could not obtain URL or anon key. Aborting."
  exit 1
fi

# ── 3. Write .env ─────────────────────────────────────────────────────────────
cat > .env <<EOF
# Auto-generated by setup.sh – do NOT commit this file
EXPO_PUBLIC_SUPABASE_URL=${API_URL}
EXPO_PUBLIC_SUPABASE_ANON=${ANON_KEY}
EOF

echo "✅  .env written:"
echo "    EXPO_PUBLIC_SUPABASE_URL=${API_URL}"
echo "    EXPO_PUBLIC_SUPABASE_ANON=${ANON_KEY:0:20}…"
echo ""

# ── 4. Apply the database migration ──────────────────────────────────────────
echo "⏳  Applying database migration (creates the users table)…"
supabase db push 2>&1
echo "✅  Migration applied."
echo ""

# ── 5. Deploy edge function ───────────────────────────────────────────────────
echo "⏳  Deploying the auth edge function…"
supabase functions deploy auth 2>&1
echo "✅  Edge function deployed."
echo ""

echo "🎉  All done!  Run your app with:  npx expo start"
echo ""
